import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 16;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const DARK_BLUE = [24, 51, 89];
const MID_GRAY = [148, 163, 184];
const TEXT_GRAY = [71, 85, 105];
const LIGHT_FILL = [245, 247, 250];

function formatDate(value) {
  if (!value) return 'Unknown';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'Unknown';

  return new Intl.DateTimeFormat('en-IN', {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
  }).format(date);
}

function formatConfidence(value) {
  if (typeof value !== 'number') return '0%';
  return `${Math.round(value * 100)}%`;
}

function loadImageAsDataUrl(src) {
  return new Promise((resolve, reject) => {
    if (!src) {
      reject(new Error('Missing image URL'));
      return;
    }

    const image = new Image();
    image.crossOrigin = 'anonymous';

    image.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = image.naturalWidth || image.width;
        canvas.height = image.naturalHeight || image.height;
        const context = canvas.getContext('2d');

        if (!context) {
          reject(new Error('Could not prepare image canvas'));
          return;
        }

        context.drawImage(image, 0, 0);
        resolve({
          dataUrl: canvas.toDataURL('image/jpeg', 0.92),
          width: canvas.width,
          height: canvas.height,
        });
      } catch (error) {
        reject(error);
      }
    };

    image.onerror = () => reject(new Error('Failed to load image'));
    image.src = src;
  });
}

function drawSeparator(doc, y) {
  doc.setDrawColor(...MID_GRAY);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
}

function ensureSpace(doc, currentY, requiredHeight) {
  if (currentY + requiredHeight <= PAGE_HEIGHT - MARGIN) {
    return currentY;
  }

  doc.addPage();
  return MARGIN;
}

function drawFooter(doc) {
  const pageCount = doc.getNumberOfPages();

  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...TEXT_GRAY);
    doc.text('Generated by ThreadCounty AI', MARGIN, PAGE_HEIGHT - 10);
    doc.text('AI Powered Textile Inspection Platform', PAGE_WIDTH / 2, PAGE_HEIGHT - 10, { align: 'center' });
    doc.text('2026', PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 10, { align: 'right' });
  }
}

export async function generateInspectionPDF(item) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const detections = Array.isArray(item?.detections) ? item.detections : [];
  const aiSummary = item?.ai_summary?.trim() || 'No AI summary available.';
  let currentY = MARGIN;

  doc.setFillColor(...LIGHT_FILL);
  doc.roundedRect(MARGIN, currentY, CONTENT_WIDTH, 28, 3, 3, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...DARK_BLUE);
  doc.text('THREADCOUNTY', MARGIN + 5, currentY + 9);
  doc.setFontSize(15);
  doc.text('AI Textile Inspection Report', MARGIN + 5, currentY + 17);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...TEXT_GRAY);
  doc.text('Professional Textile Inspection Platform', MARGIN + 5, currentY + 24);
  currentY += 36;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...DARK_BLUE);
  doc.text('Report Information', MARGIN, currentY);
  currentY += 4;
  drawSeparator(doc, currentY);
  currentY += 7;

  const infoRows = [
    ['Report ID', item?.id || 'Unknown'],
    ['Scan Date', formatDate(item?.created_at)],
    ['Processing Time', `${item?.processing_time ?? 0}s`],
    ['Confidence', formatConfidence(item?.confidence)],
    ['Total Defects', String(item?.total_defects ?? detections.length ?? 0)],
  ];

  doc.setFontSize(10.5);
  infoRows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...TEXT_GRAY);
    doc.text(`${label}:`, MARGIN, currentY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(33, 37, 41);
    doc.text(String(value), MARGIN + 34, currentY);
    currentY += 7;
  });

  currentY += 2;
  currentY = ensureSpace(doc, currentY, 70);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...DARK_BLUE);
  doc.text('Original Fabric Image', MARGIN, currentY);
  currentY += 4;
  drawSeparator(doc, currentY);
  currentY += 8;

  try {
    const image = await loadImageAsDataUrl(item?.image_url);
    const maxWidth = CONTENT_WIDTH;
    const maxHeight = 75;
    const scale = Math.min(maxWidth / image.width, maxHeight / image.height, 1);
    const renderWidth = image.width * scale;
    const renderHeight = image.height * scale;
    const imageX = MARGIN + (CONTENT_WIDTH - renderWidth) / 2;

    doc.addImage(image.dataUrl, 'JPEG', imageX, currentY, renderWidth, renderHeight);
    currentY += renderHeight + 8;
  } catch (error) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_GRAY);
    doc.text('Image unavailable for this report.', MARGIN, currentY);
    currentY += 10;
  }

  currentY = ensureSpace(doc, currentY, 35);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...DARK_BLUE);
  doc.text('Detected Defects', MARGIN, currentY);
  currentY += 4;
  drawSeparator(doc, currentY);
  currentY += 6;

  if (detections.length > 0) {
    autoTable(doc, {
      startY: currentY,
      margin: { left: MARGIN, right: MARGIN },
      head: [['Defect', 'Confidence']],
      body: detections.map((detection) => [
        detection?.class || 'Unknown',
        formatConfidence(detection?.confidence ?? 0),
      ]),
      styles: {
        font: 'helvetica',
        fontSize: 10,
        cellPadding: 3,
        textColor: [33, 37, 41],
        lineColor: [222, 226, 230],
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: DARK_BLUE,
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251],
      },
      theme: 'grid',
    });

    currentY = doc.lastAutoTable.finalY + 10;
  } else {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_GRAY);
    doc.text('No defects detected.', MARGIN, currentY);
    currentY += 10;
  }

  currentY = ensureSpace(doc, currentY, 30);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...DARK_BLUE);
  doc.text('AI Summary', MARGIN, currentY);
  currentY += 4;
  drawSeparator(doc, currentY);
  currentY += 7;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(33, 37, 41);
  const summaryLines = doc.splitTextToSize(aiSummary, CONTENT_WIDTH);
  const lineHeight = 5.5;

  summaryLines.forEach((line) => {
    currentY = ensureSpace(doc, currentY, lineHeight);
    doc.text(line, MARGIN, currentY);
    currentY += lineHeight;
  });

  drawFooter(doc);
  doc.save(`threadcounty-report-${item?.id || 'scan'}.pdf`);
}
